---
services:
  app:
    container_name: app
    env_file: .env
    build:
      dockerfile: ./Dockerfile
      args:
        PHP_BASE_IMAGE: ${PHP_BASE_IMAGE}
        ROBERT2_VERSION: ${ROBERT2_VERSION}
    ports:
      - 8000:80
    networks:
      - robert2_network
    depends_on:
      - db

  db:
    container_name: db
    image: mariadb
    command: --innodb_default_row_format=DYNAMIC --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - robert2_data:/var/lib/mysql
    networks:
      - robert2_network

# Docker Networks
networks:
  robert2_network:

# Docker volumes
volumes:
  robert2_data:
